// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220902222226_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AI")
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("IdPecuarista")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPecuarista");

                    b.ToTable("Animal", (string)null);
                });

            modelBuilder.Entity("Domain.Models.CompraGado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPecuarista")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPecuarista");

                    b.ToTable("CompraGado", (string)null);
                });

            modelBuilder.Entity("Domain.Models.CompraGadoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<int>("IdCompraGado")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAnimal");

                    b.HasIndex("IdCompraGado");

                    b.ToTable("CompraGadoItem", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Pecuarista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Pecuarista");
                });

            modelBuilder.Entity("Domain.Models.Animal", b =>
                {
                    b.HasOne("Domain.Models.Pecuarista", "Pecuarista")
                        .WithMany("Animals")
                        .HasForeignKey("IdPecuarista")
                        .IsRequired()
                        .HasConstraintName("FK_Animal_Pecuarista");

                    b.Navigation("Pecuarista");
                });

            modelBuilder.Entity("Domain.Models.CompraGado", b =>
                {
                    b.HasOne("Domain.Models.Pecuarista", "Pecuarista")
                        .WithMany("CompraGados")
                        .HasForeignKey("IdPecuarista")
                        .IsRequired()
                        .HasConstraintName("FK_CompraGado_Pecuarista");

                    b.Navigation("Pecuarista");
                });

            modelBuilder.Entity("Domain.Models.CompraGadoItem", b =>
                {
                    b.HasOne("Domain.Models.Animal", "Animal")
                        .WithMany("CompraGadoItems")
                        .HasForeignKey("IdAnimal")
                        .IsRequired()
                        .HasConstraintName("FK_CompraGadoItem_Animal");

                    b.HasOne("Domain.Models.CompraGado", "CompraGado")
                        .WithMany("CompraGadoItems")
                        .HasForeignKey("IdCompraGado")
                        .IsRequired()
                        .HasConstraintName("FK_CompraGadoItem_CompraGado");

                    b.Navigation("Animal");

                    b.Navigation("CompraGado");
                });

            modelBuilder.Entity("Domain.Models.Animal", b =>
                {
                    b.Navigation("CompraGadoItems");
                });

            modelBuilder.Entity("Domain.Models.CompraGado", b =>
                {
                    b.Navigation("CompraGadoItems");
                });

            modelBuilder.Entity("Domain.Models.Pecuarista", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("CompraGados");
                });
#pragma warning restore 612, 618
        }
    }
}
